name: Auto Update EWS

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: self-hosted
    steps:
      - name: Tarik kode dari repository
        uses: actions/checkout@v4

      - name: Jalankan Skrip Unduh & Proses
        env:
          TZ: Asia/Jakarta
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASS: ${{ secrets.FTP_PASS }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          RADAR_API_URL: ${{ secrets.RADAR_API_URL }}
          RADAR_REFERER: ${{ secrets.RADAR_REFERER }}
          AWS_GILIMANUK_URL: ${{ secrets.AWS_GILIMANUK_URL }}
          AWS_KETAPANG_URL: ${{ secrets.AWS_KETAPANG_URL }}
        run: C:/Users/anaconda/python.exe -u proses_himawari_dan_log_cb.py

      - name: Simpan Data Baru ke GitHub
        run: |
          git config --global user.name 'Robot EWS'
          git config --global user.email 'robot@bmkg.go.id'
          git add .
          if (git status --porcelain) {
            git commit -m "Auto-update data EWS"
            git push
          } else {
            echo "Tidak ada perubahan"
          }
