name: Auto Update EWS

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: self-hosted
    steps:
      # Lakukan pembersihan RAM dan proses secara paksa dari jarak jauh
      - name: Basmi Proses Menggantung (Remote Task Manager)
        run: |
          Stop-Process -Name "python" -Force -ErrorAction SilentlyContinue
          Stop-Process -Name "chrome" -Force -ErrorAction SilentlyContinue
          Stop-Process -Name "git" -Force -ErrorAction SilentlyContinue
        shell: powershell
        
      # Optimasi tingkat lanjut untuk internet tidak stabil dan file besar
      - name: Optimasi Jaringan Git (Anti Putus)
        run: |
          git config --global http.postBuffer 1048576000
          git config --global http.sslBackend openssl
          git config --global http.lowSpeedLimit 0
          git config --global http.lowSpeedTime 999999
          git config --global core.compression 0
          git config --global http.version HTTP/1.1
        shell: powershell
        
      - name: Tarik kode dari repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          clean: true

      - name: Install Dependencies
        run: C:/Users/anaconda/python.exe -m pip install beautifulsoup4

      - name: Jalankan Skrip Unduh & Proses
        env:
          TZ: Asia/Jakarta
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASS: ${{ secrets.FTP_PASS }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          RADAR_API_URL: ${{ secrets.RADAR_API_URL }}
          RADAR_REFERER: ${{ secrets.RADAR_REFERER }}
          AWS_RAW_DATA_URL: ${{ secrets.AWS_RAW_DATA_URL }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: C:/Users/anaconda/python.exe -u proses_himawari_dan_log_cb.py

      - name: Jalankan Prediksi Nowcasting Radar
        run: C:/Users/anaconda/python.exe -u nowcasting_radar.py
        
      - name: Gambar Peta Nowcasting
        run: C:/Users/anaconda/python.exe -u plot_nowcasting.py
        
      - name: Jalankan Prediksi Nowcasting Satelit
        run: C:/Users/anaconda/python.exe -u nowcasting_satelit.py

      - name: Simpan Data Baru ke GitHub
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          
          # Hapus paksa folder rebase jika macet sebelumnya
          if (Test-Path ".git\rebase-merge") { Remove-Item -Recurse -Force ".git\rebase-merge" }
          
          # Lakukan commit, abaikan error jika tidak ada perubahan
          git commit -m "Update otomatis data satelit dan radar"
          $LASTEXITCODE = 0
          
          # Tarik data dari GitHub. Jika ada konflik, paksa menangkan file lokal (-X ours)
          git pull origin main --no-rebase -X ours
          
          # Dorong hasil akhirnya ke GitHub
          git push origin main
